services:
  main-db:
    image: postgres:14
    restart: always
    ports:
      - 5431:5432
    env_file:
      - .env-compose
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username ${DB_USER} -d ${DB_NAME}"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    volumes:
      - wm-fastapi-db:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    restart: always
    ports:
      - 6380:6379
    env_file:
      - .env-compose
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_USER=${REDIS_USER}
      - REDIS_USER_PASSWORD=${REDIS_USER_PASSWORD}

volumes:
  wm-fastapi-db:
